#!/bin/bash
# reference:
#   - https://stackoverflow.com/questions/5083224/git-pull-while-not-in-a-git-directory
#     > this was how I discovered the -C option

if [[ $(which git) ]];
then git_installed=True;
else echo "[#] Please install git";
fi

if [ $git_installed ];
then
  git config core.sshCommand 'ssh -o StrictHostKeyChecking=no'
  git -C scripts/ clone ssh://admin@localhost:/git-server/repositories/admin.git
  git -C scripts/admin/ remote add master ssh://admin@localhost:/git-server/repositories/admin.git
  while true; do git -C scripts/admin/ pull; sleep 10; done
fi

